---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: codegen-b1731941135433
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-b1731941135433 
  name: codegen-b1731941135433
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi